-- AddRecipe2(
--     "ksfun_task_reel",
--     {Ingredient("cutgrass", 2)},
--     TECH.SCIENCE_ONE,
--     {
--         atlas="images/papyrus.xml",
--         image="papyrus.tex",
--     },
--     {"TOOLS"}
-- )