KSFUN_ITEMS = {
    ["cutgrass"]            = { lv = 1 },
    ["twigs"]               = { lv = 1 },
    ["rocks"]               = { lv = 1 },
    ["twigs"]               = { lv = 1 },
    ["log"]                 = { lv = 1 },
    ["poop"]                = { lv = 1 },
    ["flint"]               = { lv = 1 },
    ["charcoal"]            = { lv = 1 },
    ["cutreeds"]            = { lv = 1 },
    ["spidergland"]         = { lv = 1 },
    ["silk"]                = { lv = 1 },
    ["houndstooth"]         = { lv = 1 },
    ["stinger"]             = { lv = 1 },

    ["goldnugget"]          = { lv = 2 }, 
    ["saltrock"]            = { lv = 2 }, 
    ["livinglog"]           = { lv = 2 }, 
    ["marble"]              = { lv = 2 }, 
    ["nitre"]               = { lv = 2 }, 
    ["boneshard"]           = { lv = 2 }, 
    ["papyrus"]             = { lv = 2 },
    ["dug_grass"]           = { lv = 2 }, 
    ["dug_berrybush"]       = { lv = 2 }, 
    ["dug_berrybush2"]      = { lv = 2 },
    ["dug_berrybush_juicy"] = { lv = 2 },
    ["bullkelp_root"]       = { lv = 2 },
    ["dug_sapling"]         = { lv = 2 },


    ["waxpaper"]            = { lv = 3 }, 
    ["livinglog"]           = { lv = 3 },
    ["nightmarefuel"]       = { lv = 3 },
    ["waxpaper"]            = { lv = 3 }, 
    ["pigskin"]             = { lv = 3 }, 
    ["moonrocknugget"]      = { lv = 3 },
    ["redgem"]              = { lv = 3 }, 
    ["bluegem"]             = { lv = 3 },

    ["trunk_summer"]        = { lv = 4 }, 
    ["trunk_winter"]        = { lv = 4 }, 
    ["steelwool"]           = { lv = 4 }, 
    ["walrus_tusk"]         = { lv = 4 }, 
    ["purplegem"]           = { lv = 4 },
    ["fossil_piece"]        = { lv = 4 },
    ["gears"]               = { lv = 4 },

    ["greengem"]            = { lv = 5 }, 
    ["orangegem"]           = { lv = 5 }, 
    ["yellowgem"]           = { lv = 5 },
    ["greenstaff"]          = { lv = 5 }, 
    ["orangestaff"]         = { lv = 5 }, 
    ["yellowstaff"]         = { lv = 5 },
    ["orangeamulet"]        = { lv = 5 },
    ["yellowamulet"]        = { lv = 5 }, 
    ["greenamulet"]         = { lv = 5 }, 
 

    ["minotaurhorn"]        = { lv = 6 }, 
    ["shroom_skin"]         = { lv = 6 }, 
    ["deerclops_eyeball"]   = { lv = 6 }, 
    ["dragon_scales"]       = { lv = 6 }, 
    ["shadowheart"]         = { lv = 6 }, 
    ["ruins_bat"]           = { lv = 6 }, 
    ["townportaltalisman"]  = { lv = 6 },

    ["opalpreciousgem"]     = { lv = 7 }, 
    ["opalstaff"]           = { lv = 7 }, 

}