STRINGS.NAMES.TEST = "测试"         
STRINGS.RECIPE_DESC.TEST = "测试"
STRINGS.CHARACTERS.GENERIC.TEST= "测试"  

STRINGS.NAMES.KSFUN_ITEM = "{item}-{quality}色品质"


--- 通用属性名称
STRINGS.NAMES.KSFUN_POWER_CRIT_DAMAGE       = "暴击"
STRINGS.NAMES.KSFUN_POWER_HEALTH            = "血量增强"
STRINGS.NAMES.KSFUN_POWER_LOCOMOTOR         = "快如闪电"
STRINGS.NAMES.KSFUN_POWER_DAMAGE            = "伤害加深"


--- 角色属性名称
STRINGS.NAMES.KSFUN_POWER_PLAYER_HUNGER     = "大胃王"
STRINGS.NAMES.KSFUN_POWER_PLAYER_SANITY     = "基建狂魔"
STRINGS.NAMES.KSFUN_POWER_PLAYER_PICK       = "园艺大师"
STRINGS.NAMES.KSFUN_POWER_PLAYER_FARM       = "当代神农"


--- 物品属性名称
STRINGS.NAMES.KSFUN_POWER_ITEM_WATERPROOFER = "防水属性"
STRINGS.NAMES.KSFUN_POWER_ITEM_DAPPERNESS   = "精神恢复"
STRINGS.NAMES.KSFUN_POWER_ITEM_INSULATOR    = "气温防护"
STRINGS.NAMES.KSFUN_POWER_ITEM_DAMAGE       = "锋锐" 
STRINGS.NAMES.KSFUN_POWER_ITEM_CHOP         = "伐木"
STRINGS.NAMES.KSFUN_POWER_ITEM_MINE         = "采矿" 
STRINGS.NAMES.KSFUN_POWER_ITEM_LIFESTEAL    = "生命窃取" 
STRINGS.NAMES.KSFUN_POWER_ITEM_AOE          = "溅射伤害"


--- 怪物属性，可以不显示名称，预留
STRINGS.NAMES.KSFUN_POWER_MONSTER_REAL_DAMAGE = "真实伤害"


STRINGS.NAMES.KSFUN_TASK_KILL = "击杀任务"



STRINGS.KSFUN_FORG_FAIL_MSG_1 = "不是可以用来锻造的材料！"
STRINGS.KSFUN_FORG_FAIL_MSG_2 = "已经是最大等级了！" 
STRINGS.KSFUN_CHANGE_INSULATOR_NOTICE = "切换模式成功！"