STRINGS.NAMES.TEST = "测试"         
STRINGS.RECIPE_DESC.TEST = "测试"
STRINGS.CHARACTERS.GENERIC.TEST= "测试"  

STRINGS.NAMES.KSFUN_ITEM = "{item}-{quality}色品质"


STRINGS.NAMES.KSFUN_POWER_PLAYER_HEALTH = "血量增强"
STRINGS.NAMES.KSFUN_POWER_PLAYER_HUNGER = "饱食增强"
STRINGS.NAMES.KSFUN_POWER_PLAYER_SANITY= "精神增强"

STRINGS.NAMES.KSFUN_POWER_ITEM_WATERPROOFER = "防水属性"
STRINGS.NAMES.KSFUN_POWER_ITEM_DAPPERNESS = "精神恢复"
STRINGS.NAMES.KSFUN_POWER_ITEM_INSULATOR = "气温防护"
STRINGS.NAMES.KSFUN_POWER_ITEM_DAMAGE = "锋锐" 
STRINGS.NAMES.KSFUN_POWER_ITEM_CHOP = "伐木"
STRINGS.NAMES.KSFUN_POWER_ITEM_MINE = "采矿" 
STRINGS.NAMES.KSFUN_POWER_ITEM_LIFESTEAL = "生命窃取" 


STRINGS.NAMES.KSFUN_TASK_KILL = "击杀任务"



STRINGS.KSFUN_FORG_FAIL_MSG_1 = "不是可以用来锻造的材料！"
STRINGS.KSFUN_FORG_FAIL_MSG_2 = "已经是最大等级了！" 
STRINGS.KSFUN_CHANGE_INSULATOR_NOTICE = "切换模式成功！"